language: java

jdk:
  - openjdk15

sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:

    recipients:
      -demonick82@gmail.com
    on_success: never # default: change
    on_failure: always # default: always